[project]
name = "subscription-service-v1"
description = "A contract for managing recurring subscriptions."
authors = ["You"]
telemetry = true
cache_dir = "./.cache"

[contracts.subscription-service-v1]
path = "contracts/subscription-service.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
