[project]
name = "asset-tokenizer"
description = "Real-world asset tokenization on Stacks blockchain"
authors = ["Marcus David"]
telemetry = true
cache_dir = "./.cache"

[contracts.asset-tokenizer]
path = "contracts/asset-tokenizer.clar"
epoch = "latest"

[repl.analysis]
passes = ["check_checker"]
check_checker = { trusted_sender = false, trusted_caller = false, callee_filter = false }
